id: P010551
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:35.394567
source_metadata:
  id: bdr:W3CN3391
  title: རྒྱུད་རྒྱལ་སྒྱུ་འཕྲུལ་དྲ་བ་སྤྱི་དོན་གྱི་སྒོ་ནས་གཏན་ལ་འབེབས་པར་བྱེད་པའི་ལེགས་བཤད།
  author: ''
  volumes:
    2c9a68580e9f45edad9225e19f927039:
      image_group_id: I3CN4255
      title: ''
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
