id: I6A60C272
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:42:57+00:00'
last_modified: '2022-06-08T14:26:02.717279+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3391
  title: རྒྱུད་རྒྱལ་སྒྱུ་འཕྲུལ་དྲ་བ་སྤྱི་དོན་གྱི་སྒོ་ནས་གཏན་ལ་འབེབས་པར་བྱེད་པའི་ལེགས་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8981':
      image_group_id: I3CN4255
      title: ''
      total_pages: 248
      order: 1
      base_file: 8981.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
