id: I6A60C272
legacy_id: P010551
ocr_import_info:
  bdrc_scan_id: W3CN3391
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T12:41:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:42:46.302181+00:00'
last_modified: 2022-09-03 21:42:59.878548
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3391
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3391
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་རྒྱལ་སྒྱུ་འཕྲུལ་དྲ་བ་སྤྱི་དོན་གྱི་སྒོ་ནས་གཏན་ལ་འབེབས་པར་བྱེད་པའི་ལེགས་བཤད།
statistics:
  ocr_word_mean_confidence_index: 0.7495501504653367
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I3CN4255:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4255
      total_pages: 248
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4255.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.7495501504653367
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
